Ability to have parent event id inside response message
th2-net/th2-conn-http-client pull request #4
Opened 2021-06-25 17:11 UTC by Topru333

2021-06-30 15:07 UTC, ivandruzhinin requested changes

2021-06-30 15:07 UTC, ivandruzhinin commented on src/test/kotlin/com/exactpro/th2/http/client/ResponseTest.kt
> +package com.exactpro.th2.http.client
I don't see a need to involve network here. We should rather test that Th2RawHttpRequest behaves correctly e.g. its with* method returns an instance which retains parent event id

2021-06-30 15:59 UTC, Topru333 commented on src/main/kotlin/com/exactpro/th2/http/client/util/MessageUtil.kt
> +    val parentEventID = if (request is Th2RawHttpRequest) request.parentEventId else null
thx for good example

2021-06-30 18:18 UTC, Topru333 commented on src/main/kotlin/com/exactpro/th2/http/client/api/Th2RawHttpRequest.kt
> +        return Th2RawHttpRequest(
val newHost = RawHttpHeaders.hostHeaderValueFor(requestLine.uri) ?: error("RequestLine host must not be null")
  This one gonna throw java.lang.IllegalStateException: () -> kotlin.String coz Kotlin can't process return type of error

2021-06-30 18:24 UTC, Topru333 commented on src/main/kotlin/com/exactpro/th2/http/client/api/Th2RawHttpRequest.kt
> +        return Th2RawHttpRequest(
val newHost = RawHttpHeaders.hostHeaderValueFor(requestLine.uri) ?: error("RequestLine host must not be null")
This one gonna throw java.lang.IllegalStateException: () -> kotlin.String (in runtime) coz Kotlin can't process return type of error

2021-07-01 08:27 UTC, ivandruzhinin approved these changes

2021-07-01 08:39 UTC, merged